version: '3'

services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest-alpine
    restart: always
    pid: host
    networks:
      - traefik-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`${GLANCES_DOMAIN}`)"
      - "traefik.http.routers.glances.service=glances"
      - "traefik.http.routers.glances.entrypoints=websecure"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"
      - "traefik.http.routers.glances.tls=true"
      - "traefik.http.routers.glances.tls.certresolver=letsencrypt"
      - "traefik.http.services.glances.loadbalancer.passhostheader=true"
      - "traefik.http.routers.glances.middlewares=auth-monitoring"
      - "traefik.http.middlewares.auth-monitoring.basicauth.users=${BASIC_AUTH}"

networks:
  traefik-proxy:
    external: true
