volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/store/nextcloud/data
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/store/nextcloud/postgres

services:
  postgres:
    container_name: nextcloud-postgres
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - nextcloud
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -h 127.0.0.1"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  nextcloud:
    container_name: nextcloud
    image: nextcloud:25
    user: 1000:1000
    volumes:
      - data:/var/www/html
    networks:
      - traefik-proxy
      - nextcloud
    environment:
      POSTGRES_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_HOSTNAME: ${NEXTCLOUD_HOSTNAME}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      OVERWRITEPROTOCOL: https
      REDIS_HOST: redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_HOSTNAME}`)"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.services.nextcloud.loadbalancer.passhostheader=true"
      - "traefik.http.routers.nextcloud.middlewares=auth-nextcloud"
      - "traefik.http.middlewares.auth-nextcloud.basicauth.users=${BASIC_AUTH}"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  cron:
    image: nextcloud:25
    container_name: nextcloud-cron
    restart: unless-stopped
    volumes:
      - data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - postgres
      - redis
    networks:
      - nextcloud

  redis:
    image: redis:7
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - nextcloud

networks:
  traefik-proxy:
    external: true
  nextcloud:
