version: "3"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - /mnt/store:/srv
      - type: bind
        source: ./database.db
        target: /database.db
    networks:
      - traefik-proxy
    environment:
      - FB_BASEURL=/filebrowser
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`${FILEBROWSER_DOMAIN}`)"
      - "traefik.http.routers.filebrowser.service=filebrowser"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=letsencrypt"
      - "traefik.http.services.filebrowser.loadbalancer.passhostheader=true"
      - "traefik.http.routers.filebrowser.middlewares=auth-filebrowser"
      - "traefik.http.middlewares.auth-filebrowser.basicauth.users=${BASIC_AUTH}"
      - "traefik.docker.network=traefik-proxy"
    restart: always

volumes:
  database:


networks:
  traefik-proxy:
    external: true
